spring:
  application:
    name: licensing-service
  config:
    import: "configserver:"  # 컨피그  서버에서 설정을 가져온다는 표기
  cloud:
    config:
      uri: http://localhost:8071 # config 서버 설정
      fail-fast: true
  profiles:
    active: dev